# Wrangle

In [23]:
import pandas as pd

In [37]:
##### missile_data sheet names ######
'''
'Missile Defense Engagements',
'Locations',
'Interceptors',
'Interceptor Systems',
'Targets'
'''

# load all sheets in the file
missile_data = pd.read_excel('CNS Global Missile Defense Engagement.xlsx', 
          index_col=0, 
          sheet_name=None)

In [40]:
mde = missile_data['Missile Defense Engagements']
mde.head()

,Date_Of_Test,Launch_Time,Date_Entered/Updated,Country,Launch_Authority,Missile_Name,Target_Missile,Type_of_Launch,Launch_Location,Number_of_Interceptors,Target_Launch_Location,Intercept_Attempt_Outcome,Claimed_Intercept_Outcome,Assessed_Intercept_Outcome,Additional_Information,Sources
ID,,,,,,,,,,,,,,,,
1,1999-10-02,NaT,2019-01-16,USA,BMDO,Ground-Based Interceptor,Long Range Ballistic Missile,Intercept test,Meck Island,1.0,Vandenberg Air Force Base,Successful Intercept,NaN,NaN,The first intercept test for the GMD system. T...,http://www.dote.osd.mil/pub/reports/fy1999/pdf...
2,2000-01-18,2000-01-18 22:40:00,2019-01-16,USA,BMDO,Ground-Based Interceptor,Long Range Ballistic Missile,Intercept test,Meck Island,1.0,Vandenberg Air Force Base,Unsuccessful Intercept,NaN,NaN,The intercept test failed after a cooling pipe...,http://www.bits.de/NRANEU/BMD/documents/IFT4.p...
3,2000-07-08,NaT,2019-01-16,USA,BMDO,Ground-Based Interceptor,Long Range Ballistic Missile,Intercept test,Meck Island,1.0,Vandenberg Air Force Base,Unsuccessful Intercept,NaN,NaN,This was the first intercept test attempt to u...,http://www.dote.osd.mil/pub/reports/fy1999/pdf...
4,2001-07-14,NaT,2019-01-16,USA,BMDO,Ground-Based Interceptor,Long Range Ballistic Missile,Intercept test,Meck Island,1.0,Vandenberg Air Force Base,Successful Intercept,NaN,NaN,It is not clear what kind of missile the targ...,https://boeing.mediaroom.com/2001-07-15-Boeing...
5,2001-12-03,NaT,2019-01-18,USA,BMDO,Ground-Based Interceptor,Long Range Ballistic Missile,Intercept test,Meck Island,1.0,Vandenberg Air Force Base,Successful Intercept,NaN,NaN,The test was effectively a repeat of the previ...,http://www.spacearchive.info/osptlv-ift-7.htm;...

In [42]:
mde.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365 entries, 1 to 371
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date_Of_Test                365 non-null    datetime64[ns]
 1   Launch_Time                 97 non-null     datetime64[ns]
 2   Date_Entered/Updated        365 non-null    datetime64[ns]
 3   Country                     365 non-null    object
 4   Launch_Authority            365 non-null    object
 5   Missile_Name                365 non-null    object
 6   Target_Missile              365 non-null    object
 7   Type_of_Launch              365 non-null    object
 8   Launch_Location             365 non-null    object
 9   Number_of_Interceptors      218 non-null    float64
 10  Target_Launch_Location      360 non-null    object
 11  Intercept_Attempt_Outcome   221 non-null    object
 12  Claimed_Intercept_Outcome   144 non-null    object
 13  Assessed_Intercept_Outcome  144 non-null    object
 14  Additional_Information      309 non-null    object
 15  Sources                     364 non-null    object
dtypes: datetime64[ns](3), float64(1), object(12)
memory usage: 48.5+ KB

In [43]:
mde.describe()

,Date_Of_Test,Launch_Time,Date_Entered/Updated,Number_of_Interceptors
count,365,97,365,218.000000
mean,2008-01-09 17:13:38.630137088,2001-08-22 18:29:11.752577536,2019-05-26 21:26:08.219177984,1.357798
min,1960-12-08 00:00:00,1991-01-20 18:43:00,2018-06-14 00:00:00,1.000000
25%,2001-10-19 00:00:00,1991-01-26 00:28:00,2019-03-27 00:00:00,1.000000
50%,2012-10-24 00:00:00,2003-03-20 09:24:00,2019-04-16 00:00:00,1.000000
75%,2017-06-21 00:00:00,2011-04-15 06:52:00,2019-09-17 00:00:00,1.000000
max,2019-11-06 00:00:00,2019-03-27 05:39:00,2019-12-04 00:00:00,7.000000
std,NaN,NaN,NaN,0.940859